# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import deepfocus_pb2 as deepfocus__pb2


class DeepFocusStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateCalibrationCurve = channel.unary_unary(
        '/DeepFocusGUI.DeepFocus/CreateCalibrationCurve',
        request_serializer=deepfocus__pb2.CalibrationRequest.SerializeToString,
        response_deserializer=deepfocus__pb2.CalibrationCurve.FromString,
        )
    self.StartAutofocus = channel.unary_unary(
        '/DeepFocusGUI.DeepFocus/StartAutofocus',
        request_serializer=deepfocus__pb2.BestFocusRequest.SerializeToString,
        response_deserializer=deepfocus__pb2.BestFocusResponse.FromString,
        )
    self.LoadCalibration = channel.unary_unary(
        '/DeepFocusGUI.DeepFocus/LoadCalibration',
        request_serializer=deepfocus__pb2.CurveRequest.SerializeToString,
        response_deserializer=deepfocus__pb2.CurveResponse.FromString,
        )


class DeepFocusServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateCalibrationCurve(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StartAutofocus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LoadCalibration(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DeepFocusServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateCalibrationCurve': grpc.unary_unary_rpc_method_handler(
          servicer.CreateCalibrationCurve,
          request_deserializer=deepfocus__pb2.CalibrationRequest.FromString,
          response_serializer=deepfocus__pb2.CalibrationCurve.SerializeToString,
      ),
      'StartAutofocus': grpc.unary_unary_rpc_method_handler(
          servicer.StartAutofocus,
          request_deserializer=deepfocus__pb2.BestFocusRequest.FromString,
          response_serializer=deepfocus__pb2.BestFocusResponse.SerializeToString,
      ),
      'LoadCalibration': grpc.unary_unary_rpc_method_handler(
          servicer.LoadCalibration,
          request_deserializer=deepfocus__pb2.CurveRequest.FromString,
          response_serializer=deepfocus__pb2.CurveResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DeepFocusGUI.DeepFocus', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
